// Generated by Wrangler on Thu Jul 18 2024 13:48:58 GMT+0100 (West Africa Standard Time)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	DATABASE_URL: string;
	TRIGGER_API_URL: string;
	TRIGGER_API_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUPABASE_URL: string;
}
