// Generated by Wrangler on Wed Jul 24 2024 07:39:58 GMT+0100 (West Africa Standard Time)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	TRIGGER_API_KEY: string;
	DATABASE_URL: string;
	G00GLE_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
}
