// Generated by Wrangler on Thu Jul 25 2024 21:37:04 GMT+0100 (West Africa Standard Time)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	APP_URL: string;
	API_URL: string;
	TRIGGER_API_KEY: string;
	DATABASE_URL: string;
	G00GLE_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	PLUNK_API_KEY: string;
	EMAIL_DOMAIN: string;
}
