name = "innkeeper-api"
compatibility_date = "2024-07-16"

# [[env.staging.d1_databases]]
# binding = "DB"
# database_name = "db-staging"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[env.production.d1_databases]] 
# binding = "DB"  
# database_name = "db-production"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[env.production.ai]]
# binding = "AI"

[[env.staging.ai]]
# binding = "AI"

# [env.staging.vars]
# ENVIRONMENT = "staging"

# [env.production.vars]
# ENVIRONMENT = "production"
