node_compat = true
name = "innkeeper-api"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_als"]

vars = { ENVIRONMENT = "development", TRIGGER_API_KEY = "", DATABASE_URL = "", GOOGLE_CLIENT_ID = "", G00GLE_CLIENT_SECRET = "" }
# d1_databases = [
#    { binding = "DB", database_name = "innkeeper", database_id = "DATABASE_ID" },
# ]

[env.production]
vars = { ENVIRONMENT = "production", TRIGGER_API_KEY = "", DATABASE_URL = "", GOOGLE_CLIENT_ID = "", G00GLE_CLIENT_SECRET = "" }
# d1_databases = [
#     { binding = "DB", database_name = "innkeeper_production", database_id = "PRODUCTION_DB_ID" },
# ]
