name = "innkeeper-api"
compatibility_date = "2024-07-16"

d1_databases = [
    { binding = "DB", database_name = "innkeeper", database_id = "DATABASE_ID" },
]
vars = { ENVIRONMENT = "development", INNGEST_EVENT_KEY = "your_ingest_event_key", TRIGGER_API_KEY = "xxx", TRIGGER_API_URL = "xxx" }

[env.production]
d1_databases = [
    { binding = "DB", database_name = "innkeeper_production", database_id = "PRODUCTION_DB_ID" },
]
vars = { ENVIRONMENT = "production", INNGEST_EVENT_KEY = "your_ingest_event_key", TRIGGER_API_KEY = "xxxxxxx", TRIGGER_API_URL = "xxxxx" }
